#############################################################################
# Makefile for building: librun_tracker.so
# Generated by qmake (3.1) (Qt 5.11.0)
# Project:  run_tracker.pro
# Template: app
# Command: C:\Qt5_11_intel\5.11.0\android_x86\bin\qmake.exe -o Makefile run_tracker.pro -spec android-g++ "CONFIG+=qtquickcompiler"
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = C:\Android\android-ndk-r16/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-gcc
CXX           = C:\Android\android-ndk-r16/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-g++
DEFINES       = -DQT_NO_DEBUG -DQT_LOCATION_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_POSITIONING_LIB -DQT_CONCURRENT_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_ANDROIDEXTRAS_LIB -DQT_CORE_LIB
CFLAGS        = -D__ANDROID_API__=16 --sysroot=C:\Android\android-ndk-r16/sysroot -isystem C:\Android\android-ndk-r16/sysroot/usr/include/i686-linux-android -isystem C:\Android\android-ndk-r16/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem C:\Android\android-ndk-r16/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -fstack-protector-strong -DANDROID -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -D__ANDROID_API__=16 --sysroot=C:\Android\android-ndk-r16/sysroot -isystem C:\Android\android-ndk-r16/sysroot/usr/include/i686-linux-android -isystem C:\Android\android-ndk-r16/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem C:\Android\android-ndk-r16/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -fstack-protector-strong -DANDROID -O2 -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I..\..\Qt5_11_intel\5.11.0\android_x86\include -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtLocation -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQuick -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtConcurrent -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtNetwork -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras -I..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore -I. -I..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\android-g++
QMAKE         = C:\Qt5_11_intel\5.11.0\android_x86\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt5_11_intel\5.11.0\android_x86\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt5_11_intel\5.11.0\android_x86\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = librun_tracker.so1.0.0
DISTDIR = C:\QtGitProject\run_tracker\.tmp\librun_tracker.so1.0.0
LINK          = C:\Android\android-ndk-r16/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-g++
LFLAGS        = --sysroot=C:\Android\android-ndk-r16/platforms/android-16/arch-x86/ -Wl,-soname,librun_tracker.so -Wl,-rpath=C:/Qt5_11_intel/5.11.0/android_x86/lib -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LC:\Android\android-ndk-r16/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86 -Lc:/android/android-ndk-r16/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x -LC:/Qt5_11_intel/5.11.0/android_x86/lib -lQt5Location -Lc:\utils\android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86 -Lc:/utils/android-ndk-r10e/toolchains/x86-4.9/prebuilt/windows/bin/../lib/gcc/i686-linux-android/4.9 -LC:\Qt5_11_intel\5.11.0\android_x86/lib -lQt5Quick -lQt5Gui -lQt5Positioning -lQt5Concurrent -lQt5Qml -lQt5Network -lQt5Sql -lQt5AndroidExtras -lQt5Core -lGLESv2 -lgnustl_shared -lgcc -llog -lz -lm -ldl -lc
AR            = C:\Android\android-ndk-r16/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ar cqs
RANLIB        = C:\Android\android-ndk-r16/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-ranlib
SED           = $(QMAKE) -install sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = databasecoord.cpp \
		main.cpp \
		qualitygpssignal.cpp \
		battery_parametres.cpp qrc_qml_qmlcache.cpp \
		Newrun_qml.cpp \
		Historyrun_qml.cpp \
		Grid_newrun_qml.cpp \
		DeleteDialog_qml.cpp \
		LowsignalDialog_qml.cpp \
		Settings_qml.cpp \
		ExitDialog_qml.cpp \
		Menubar_qml.cpp \
		main_qml.cpp \
		jscode_functionparam_js.cpp \
		qmlcache_loader.cpp \
		moc_databasecoord.cpp \
		moc_qualitygpssignal.cpp \
		moc_battery_parametres.cpp
OBJECTS       = databasecoord.obj \
		main.obj \
		qualitygpssignal.obj \
		battery_parametres.obj \
		qrc_qml_qmlcache.obj \
		Newrun_qml.obj \
		Historyrun_qml.obj \
		Grid_newrun_qml.obj \
		DeleteDialog_qml.obj \
		LowsignalDialog_qml.obj \
		Settings_qml.obj \
		ExitDialog_qml.obj \
		Menubar_qml.obj \
		main_qml.obj \
		jscode_functionparam_js.obj \
		qmlcache_loader.obj \
		moc_databasecoord.obj \
		moc_qualitygpssignal.obj \
		moc_battery_parametres.obj
DIST          = main.qml \
		ExitDialog.qml \
		Newrun.qml \
		Historyrun.qml \
		image\delete_button.png \
		Rowstartstop.qml \
		Rectangletimer.qml \
		LowsignalDialog.qml \
		settings_logic.js \
		DeleteDialog.qml \
		Settings.qml \
		Settings_object.qml \
		android\src\org\producer\egor\run_tracker\NotificationClient.java \
		android\AndroidManifest.xml databasecoord.h \
		qualitygpssignal.h \
		battery_parametres.h databasecoord.cpp \
		main.cpp \
		qualitygpssignal.cpp \
		battery_parametres.cpp
QMAKE_TARGET  = librun_tracker.so
DESTDIR       = 
TARGET        = librun_tracker.so


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: run_tracker.pro ..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\android-g++\qmake.conf ..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\spec_pre.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\unix.conf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\linux.conf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\sanitize.conf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\gcc-base.conf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\gcc-base-unix.conf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\qdevice.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\device_config.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\android-base-head.conf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\qconfig.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3drender.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_androidextras.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_androidextras_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_core.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_core_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_gui.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_help.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_help_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_input_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_location.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_location_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_network.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_network_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_nfc.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_opengl.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_positioning.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qml.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quick.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_scxml.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_serialport.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_service_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_sql.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_svg.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_uitools.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_websockets.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_webview.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_xml.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qt_functions.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qt_config.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\android-base-tail.conf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\android-g++\qmake.conf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\exclusive_builds.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\toolchain.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\default_pre.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\resolve_config.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\default_post.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\resources.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qtquickcompiler.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\android\android.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\android\android_deployment_settings.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\warn_on.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qt.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\moc.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\unix\opengl.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\unix\thread.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qmake_use.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\file_copies.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\testcase_targets.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\exceptions.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\yacc.prf \
		..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\lex.prf \
		run_tracker.pro \
		qml_qmlcache.qrc \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Location.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Quick.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Gui.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Positioning.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Concurrent.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Qml.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Network.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Sql.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5AndroidExtras.prl \
		..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Core.prl
	$(QMAKE) -o Makefile run_tracker.pro -spec android-g++ "CONFIG+=qtquickcompiler"
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\spec_pre.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\unix.conf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\linux.conf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\sanitize.conf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\gcc-base.conf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\gcc-base-unix.conf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\qdevice.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\device_config.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\android-base-head.conf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\qconfig.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3danimation.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dcore.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dextras.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dinput.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquick.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3drender.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_androidextras.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_androidextras_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_core.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_gamepad.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_help.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_help_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_input_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_location.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_location_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_network.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_positioning.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_scxml.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_serialbus.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_service_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_webview.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_webview_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qt_functions.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qt_config.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\common\android-base-tail.conf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\android-g++\qmake.conf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\exclusive_builds.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\toolchain.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\default_pre.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\resolve_config.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\default_post.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\resources.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qtquickcompiler.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\android\android.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\android\android_deployment_settings.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\warn_on.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qt.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\moc.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\unix\opengl.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\unix\thread.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\qmake_use.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\file_copies.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\testcase_targets.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\exceptions.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\yacc.prf:
..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\lex.prf:
run_tracker.pro:
qml_qmlcache.qrc:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Location.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Quick.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Gui.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Positioning.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Concurrent.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Qml.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Network.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Sql.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5AndroidExtras.prl:
..\..\Qt5_11_intel\5.11.0\android_x86\lib\libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile run_tracker.pro -spec android-g++ "CONFIG+=qtquickcompiler"

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`\$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)\
	$(COPY_FILE) --parents qml_qmlcache.qrc $(DISTDIR)\
	$(COPY_FILE) --parents Newrun.qml Historyrun.qml Grid_newrun.qml DeleteDialog.qml LowsignalDialog.qml Settings.qml ExitDialog.qml Menubar.qml main.qml jscode\functionparam.js $(DISTDIR)\
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)\
	$(COPY_FILE) --parents ..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\data\dummy.cpp $(DISTDIR)\
	$(COPY_FILE) --parents databasecoord.h qualitygpssignal.h battery_parametres.h $(DISTDIR)\
	$(COPY_FILE) --parents databasecoord.cpp main.cpp qualitygpssignal.cpp battery_parametres.cpp $(DISTDIR)\


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml_qmlcache.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml_qmlcache.cpp
qrc_qml_qmlcache.cpp: qml_qmlcache.qrc \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\rcc.exe \
		image\running_man.png \
		image\iconhamburger.png \
		image\level0.png \
		image\level1.png \
		image\level2.png \
		image\unlock3.png \
		image\level3.png \
		image\history.png \
		image\exit2.png \
		image\Cast_Glass_1.png \
		image\Cast_Glass_2.png \
		image\start_new.png \
		image\press_start_new.png \
		image\delete_button3.png \
		image\now_position.png \
		image\History_list.png \
		image\lock3.png \
		image\settings_icon.png \
		image\Pause-icon.png \
		image\stop.png
	C:\Qt5_11_intel\5.11.0\android_x86\bin\rcc.exe -name qml_qmlcache qml_qmlcache.qrc -o qrc_qml_qmlcache.cpp

compiler_qmlcache_make_all: Newrun_qml.cpp Historyrun_qml.cpp Grid_newrun_qml.cpp DeleteDialog_qml.cpp LowsignalDialog_qml.cpp Settings_qml.cpp ExitDialog_qml.cpp Menubar_qml.cpp main_qml.cpp jscode_functionparam_js.cpp
compiler_qmlcache_clean:
	-$(DEL_FILE) Newrun_qml.cpp Historyrun_qml.cpp Grid_newrun_qml.cpp DeleteDialog_qml.cpp LowsignalDialog_qml.cpp Settings_qml.cpp ExitDialog_qml.cpp Menubar_qml.cpp main_qml.cpp jscode_functionparam_js.cpp
Newrun_qml.cpp: Newrun.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o Newrun_qml.cpp Newrun.qml

Historyrun_qml.cpp: Historyrun.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o Historyrun_qml.cpp Historyrun.qml

Grid_newrun_qml.cpp: Grid_newrun.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o Grid_newrun_qml.cpp Grid_newrun.qml

DeleteDialog_qml.cpp: DeleteDialog.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o DeleteDialog_qml.cpp DeleteDialog.qml

LowsignalDialog_qml.cpp: LowsignalDialog.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o LowsignalDialog_qml.cpp LowsignalDialog.qml

Settings_qml.cpp: Settings.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o Settings_qml.cpp Settings.qml

ExitDialog_qml.cpp: ExitDialog.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o ExitDialog_qml.cpp ExitDialog.qml

Menubar_qml.cpp: Menubar.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o Menubar_qml.cpp Menubar.qml

main_qml.cpp: main.qml \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o main_qml.cpp main.qml

jscode_functionparam_js.cpp: jscode\functionparam.js \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource=C:/QtGitProject/run_tracker/qml.qrc -o jscode_functionparam_js.cpp jscode\functionparam.js

compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
qmlcache_loader.cpp: qml.qrc ..\..\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\qmlcachegen.exe --resource-file-mapping="C:/QtGitProject/run_tracker/qml.qrc=C:/QtGitProject/run_tracker/qml_qmlcache.qrc" -o qmlcache_loader.cpp qml.qrc

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\data\dummy.cpp
	C:\Android\android-ndk-r16/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-g++ -D__ANDROID_API__=16 --sysroot=C:\Android\android-ndk-r16/sysroot -isystem C:\Android\android-ndk-r16/sysroot/usr/include/i686-linux-android -isystem C:\Android\android-ndk-r16/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem C:\Android\android-ndk-r16/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -fstack-protector-strong -DANDROID -O2 -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ..\..\Qt5_11_intel\5.11.0\android_x86\mkspecs\features\data\dummy.cpp

compiler_moc_header_make_all: moc_databasecoord.cpp moc_qualitygpssignal.cpp moc_battery_parametres.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_databasecoord.cpp moc_qualitygpssignal.cpp moc_battery_parametres.cpp
moc_databasecoord.cpp: ..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnamespace.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig-bootstrapped.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtcore-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsystemdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qprocessordetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcompilerdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtypeinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsysinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlogging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qflags.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbasicatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_bootstrap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qgenericatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_cxx11.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobalstatic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmutex.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnumeric.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qversiontagging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstring.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qchar.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrefcount.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qarraydata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringliteral.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringview.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringbuilder.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiterator.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhashfunctions.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpair.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearraylist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qregexp.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringmatcher.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcoreevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qscopedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmetatype.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvarlengtharray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontainerfwd.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSql \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qtsqlglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSqlDatabase \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qsqldatabase.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSqlQuery \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qsqlquery.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QStringListModel \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlistmodel.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qabstractitemmodel.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvariant.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdebug.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhash.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtextstream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiodevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlocale.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qshareddata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvector.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpoint.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qset.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontiguouscache.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer_impl.h \
		databasecoord.h \
		moc_predefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\moc.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\moc.exe $(DEFINES) --include ./moc_predefs.h -IC:/Qt5_11_intel/5.11.0/android_x86/mkspecs/android-g++ -IC:/QtGitProject/run_tracker -IC:/Qt5_11_intel/5.11.0/android_x86/include -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtLocation -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtQuick -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtGui -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtPositioning -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtConcurrent -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtQml -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtNetwork -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtSql -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtAndroidExtras -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtCore -IC:/Qt/Qt5.10.0/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Qt5.10.0/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward databasecoord.h -o moc_databasecoord.cpp

moc_qualitygpssignal.cpp: ..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnamespace.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig-bootstrapped.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtcore-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsystemdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qprocessordetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcompilerdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtypeinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsysinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlogging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qflags.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbasicatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_bootstrap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qgenericatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_cxx11.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobalstatic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmutex.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnumeric.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qversiontagging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstring.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qchar.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrefcount.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qarraydata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringliteral.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringview.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringbuilder.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiterator.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhashfunctions.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpair.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearraylist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qregexp.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringmatcher.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcoreevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qscopedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmetatype.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvarlengtharray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontainerfwd.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\QGeoSatelliteInfoSource \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qgeosatelliteinfosource.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\QGeoSatelliteInfo \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qgeosatelliteinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qpositioningglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QList \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\QList \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtguiglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtgui-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qwindowdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qwindowdefs_win.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qregion.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrect.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmargins.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsize.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpoint.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdatastream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiodevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qkeysequence.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvariant.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdebug.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhash.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtextstream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlocale.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qshareddata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvector.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qset.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontiguouscache.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qurl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qurlquery.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qfile.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qfiledevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qvector2d.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtouchdevice.h \
		qualitygpssignal.h \
		moc_predefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\moc.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\moc.exe $(DEFINES) --include ./moc_predefs.h -IC:/Qt5_11_intel/5.11.0/android_x86/mkspecs/android-g++ -IC:/QtGitProject/run_tracker -IC:/Qt5_11_intel/5.11.0/android_x86/include -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtLocation -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtQuick -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtGui -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtPositioning -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtConcurrent -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtQml -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtNetwork -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtSql -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtAndroidExtras -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtCore -IC:/Qt/Qt5.10.0/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Qt5.10.0/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward qualitygpssignal.h -o moc_qualitygpssignal.cpp

moc_battery_parametres.cpp: ..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnamespace.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig-bootstrapped.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtcore-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsystemdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qprocessordetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcompilerdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtypeinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsysinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlogging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qflags.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbasicatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_bootstrap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qgenericatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_cxx11.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobalstatic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmutex.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnumeric.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qversiontagging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstring.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qchar.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrefcount.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qarraydata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringliteral.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringview.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringbuilder.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiterator.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhashfunctions.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpair.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearraylist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qregexp.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringmatcher.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcoreevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qscopedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmetatype.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvarlengtharray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontainerfwd.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\QAndroidJniObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\qandroidjniobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\qandroidextrasglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qshareddata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhash.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer_impl.h \
		battery_parametres.h \
		moc_predefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\bin\moc.exe
	C:\Qt5_11_intel\5.11.0\android_x86\bin\moc.exe $(DEFINES) --include ./moc_predefs.h -IC:/Qt5_11_intel/5.11.0/android_x86/mkspecs/android-g++ -IC:/QtGitProject/run_tracker -IC:/Qt5_11_intel/5.11.0/android_x86/include -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtLocation -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtQuick -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtGui -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtPositioning -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtConcurrent -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtQml -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtNetwork -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtSql -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtAndroidExtras -IC:/Qt5_11_intel/5.11.0/android_x86/include/QtCore -IC:/Qt/Qt5.10.0/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Qt5.10.0/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Qt5.10.0/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward battery_parametres.h -o moc_battery_parametres.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_qmlcache_clean compiler_qmlcache_loader_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

databasecoord.obj: databasecoord.cpp databasecoord.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnamespace.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig-bootstrapped.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtcore-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsystemdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qprocessordetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcompilerdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtypeinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsysinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlogging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qflags.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbasicatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_bootstrap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qgenericatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_cxx11.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobalstatic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmutex.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnumeric.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qversiontagging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstring.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qchar.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrefcount.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qarraydata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringliteral.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringview.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringbuilder.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiterator.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhashfunctions.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpair.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearraylist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qregexp.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringmatcher.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcoreevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qscopedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmetatype.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvarlengtharray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontainerfwd.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSql \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qtsqlglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSqlDatabase \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qsqldatabase.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSqlQuery \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qsqlquery.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QStringListModel \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlistmodel.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qabstractitemmodel.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvariant.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdebug.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhash.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtextstream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiodevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlocale.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qshareddata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvector.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpoint.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qset.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontiguouscache.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QDebug \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QDate \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databasecoord.obj databasecoord.cpp

main.obj: main.cpp ..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\QGuiApplication \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qguiapplication.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtguiglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig-bootstrapped.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtcore-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsystemdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qprocessordetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcompilerdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtypeinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsysinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlogging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qflags.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbasicatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_bootstrap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qgenericatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_cxx11.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobalstatic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmutex.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnumeric.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qversiontagging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtgui-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcoreapplication.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstring.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qchar.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrefcount.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnamespace.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qarraydata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringliteral.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringview.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringbuilder.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiterator.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhashfunctions.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpair.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearraylist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qregexp.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringmatcher.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcoreevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qscopedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmetatype.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvarlengtharray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontainerfwd.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qeventloop.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qwindowdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qwindowdefs_win.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qinputmethod.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlocale.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvariant.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdebug.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhash.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtextstream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiodevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvector.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpoint.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qset.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontiguouscache.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qshareddata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsize.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\QQmlApplicationEngine \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmlapplicationengine.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmlengine.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qurl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qurlquery.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qjsengine.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qjsvalue.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qtqmlglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qtqml-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtNetwork\qtnetworkglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtNetwork\qtnetwork-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmldebug.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqml.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmlprivate.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmlparserstatus.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmlpropertyvaluesource.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmllist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmetaobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmlerror.h \
		databasecoord.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSql \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qtsqlglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSqlDatabase \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qsqldatabase.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\QSqlQuery \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtSql\qsqlquery.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QStringListModel \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlistmodel.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qabstractitemmodel.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\QQmlContext \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtQml\qqmlcontext.h \
		qualitygpssignal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\QGeoSatelliteInfoSource \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qgeosatelliteinfosource.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\QGeoSatelliteInfo \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qgeosatelliteinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qpositioningglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QList \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\QList \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qregion.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrect.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmargins.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdatastream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qkeysequence.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qfile.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qfiledevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qvector2d.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtouchdevice.h \
		battery_parametres.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\QAndroidJniObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\qandroidjniobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\qandroidextrasglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

qualitygpssignal.obj: qualitygpssignal.cpp qualitygpssignal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnamespace.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig-bootstrapped.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtcore-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsystemdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qprocessordetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcompilerdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtypeinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsysinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlogging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qflags.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbasicatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_bootstrap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qgenericatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_cxx11.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobalstatic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmutex.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnumeric.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qversiontagging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstring.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qchar.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrefcount.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qarraydata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringliteral.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringview.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringbuilder.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiterator.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhashfunctions.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpair.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearraylist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qregexp.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringmatcher.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcoreevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qscopedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmetatype.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvarlengtharray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontainerfwd.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\QGeoSatelliteInfoSource \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qgeosatelliteinfosource.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\QGeoSatelliteInfo \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qgeosatelliteinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtPositioning\qpositioningglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QList \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\QList \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtguiglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtgui-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qwindowdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qwindowdefs_win.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qregion.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrect.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmargins.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsize.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpoint.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdatastream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiodevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qkeysequence.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvariant.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdebug.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhash.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtextstream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlocale.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qshareddata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvector.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qset.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontiguouscache.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qurl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qurlquery.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qfile.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qfiledevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qvector2d.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtGui\qtouchdevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qualitygpssignal.obj qualitygpssignal.cpp

battery_parametres.obj: battery_parametres.cpp battery_parametres.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnamespace.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig-bootstrapped.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qconfig.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtcore-config.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsystemdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qprocessordetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcompilerdetection.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtypeinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsysinfo.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlogging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qflags.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbasicatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_bootstrap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qgenericatomic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qatomic_cxx11.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qglobalstatic.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmutex.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qnumeric.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qversiontagging.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobjectdefs_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstring.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qchar.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qrefcount.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qarraydata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringliteral.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringview.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringbuilder.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qalgorithms.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiterator.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhashfunctions.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpair.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qbytearraylist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringlist.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qregexp.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qstringmatcher.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcoreevent.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qscopedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmetatype.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvarlengtharray.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontainerfwd.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qobject_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\QAndroidJniObject \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\qandroidjniobject.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtAndroidExtras\qandroidextrasglobal.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qshareddata.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qhash.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qsharedpointer_impl.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\QDebug \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qdebug.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qmap.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qtextstream.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qiodevice.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qlocale.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvariant.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qvector.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qpoint.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qset.h \
		..\..\Qt5_11_intel\5.11.0\android_x86\include\QtCore\qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o battery_parametres.obj battery_parametres.cpp

qrc_qml_qmlcache.obj: qrc_qml_qmlcache.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml_qmlcache.obj qrc_qml_qmlcache.cpp

Newrun_qml.obj: Newrun_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Newrun_qml.obj Newrun_qml.cpp

Historyrun_qml.obj: Historyrun_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Historyrun_qml.obj Historyrun_qml.cpp

Grid_newrun_qml.obj: Grid_newrun_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grid_newrun_qml.obj Grid_newrun_qml.cpp

DeleteDialog_qml.obj: DeleteDialog_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeleteDialog_qml.obj DeleteDialog_qml.cpp

LowsignalDialog_qml.obj: LowsignalDialog_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LowsignalDialog_qml.obj LowsignalDialog_qml.cpp

Settings_qml.obj: Settings_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settings_qml.obj Settings_qml.cpp

ExitDialog_qml.obj: ExitDialog_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ExitDialog_qml.obj ExitDialog_qml.cpp

Menubar_qml.obj: Menubar_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Menubar_qml.obj Menubar_qml.cpp

main_qml.obj: main_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_qml.obj main_qml.cpp

jscode_functionparam_js.obj: jscode_functionparam_js.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jscode_functionparam_js.obj jscode_functionparam_js.cpp

qmlcache_loader.obj: qmlcache_loader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlcache_loader.obj qmlcache_loader.cpp

moc_databasecoord.obj: moc_databasecoord.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databasecoord.obj moc_databasecoord.cpp

moc_qualitygpssignal.obj: moc_qualitygpssignal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qualitygpssignal.obj moc_qualitygpssignal.cpp

moc_battery_parametres.obj: moc_battery_parametres.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_battery_parametres.obj moc_battery_parametres.cpp

####### Install

install_target: first FORCE
	@if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\x86 mkdir $(INSTALL_ROOT:@msyshack@%=%)\libs\x86 & if not exist $(INSTALL_ROOT:@msyshack@%=%)\libs\x86 exit 1
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT:@msyshack@%=%)\libs\x86\$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT:@msyshack@%=%)\libs\x86\$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT:@msyshack@%=%)\libs\x86 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

